// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLj5CA2ZfuwQQe46XEkXJ18W8G_FI3Q8A',
    appId: '1:555617500653:web:1de3c27f3641f909917be4',
    messagingSenderId: '555617500653',
    projectId: 'velocy-app',
    authDomain: 'velocy-app.firebaseapp.com',
    storageBucket: 'velocy-app.firebasestorage.app',
    measurementId: 'G-FYQE499PDL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARgmZ-7AiMHT2bfR9K0eWo0kZMTWUYsdQ',
    appId: '1:555617500653:android:b431662847c9b225917be4',
    messagingSenderId: '555617500653',
    projectId: 'velocy-app',
    storageBucket: 'velocy-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKcIQxZjOfuQWWtSuegPMtRbBqhU3JFGk',
    appId: '1:555617500653:ios:0b83d707992b14ed917be4',
    messagingSenderId: '555617500653',
    projectId: 'velocy-app',
    storageBucket: 'velocy-app.firebasestorage.app',
    iosBundleId: 'com.example.velocyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKcIQxZjOfuQWWtSuegPMtRbBqhU3JFGk',
    appId: '1:555617500653:ios:0b83d707992b14ed917be4',
    messagingSenderId: '555617500653',
    projectId: 'velocy-app',
    storageBucket: 'velocy-app.firebasestorage.app',
    iosBundleId: 'com.example.velocyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLj5CA2ZfuwQQe46XEkXJ18W8G_FI3Q8A',
    appId: '1:555617500653:web:a718b46ea90efdff917be4',
    messagingSenderId: '555617500653',
    projectId: 'velocy-app',
    authDomain: 'velocy-app.firebaseapp.com',
    storageBucket: 'velocy-app.firebasestorage.app',
    measurementId: 'G-DEBTCLZTWL',
  );

}